theme: jekyll-theme-leap-day
title: Mathgens
permalink: pretty
collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
